/**
 * Bounded public competitor intelligence for the content engine. This is an
 * editorial input, not a crawler: it stores only page-level metadata observed
 * during a scheduled research review and never stores competitor article copy.
 */
export type CompetitorPageType = "COMMERCIAL_PRODUCT" | "TEMPLATE" | "HOW_TO" | "TOOL" | "RESOURCE" | "PRICING" | "HELP";
export type SeoPriority = "P0" | "P1" | "P2";
export type SeoRecommendation = "NEW" | "EXPAND_EXISTING" | "IGNORE";

export interface CompetitorSeoPage {
  competitor: "Instrumentl" | "Foundant / GrantHub" | "AmpliFund" | "Submittable" | "Fluxx";
  url: string;
  title: string;
  pageType: CompetitorPageType;
  intent: string;
  observedAt: string;
}

export interface SeoGrowthOpportunity {
  id: string;
  priority: SeoPriority;
  primaryQuery: string;
  userIntent: string;
  proposedUrl: string;
  title: string;
  pageType: "COMMERCIAL_LANDING_PAGE" | "TEMPLATE" | "PILLAR_GUIDE" | "ARTICLE" | "COMPARISON" | "CHECKLIST";
  recommendation: SeoRecommendation;
  existingPrimaryUrl?: string;
  competitorEvidence: string[];
  differentiatedValue: string;
  postAwardFit: number;
  commercialIntent: number;
  productAlignment: number;
  freeFirstAwardFit: number;
  contentGap: number;
  templatePotential: number;
  competition: "LOW" | "MEDIUM" | "HIGH" | "UNKNOWN";
  priorityScore: number;
  sourceSignals: Array<"COMPETITOR_GAP" | "COMMERCIAL_INTENT" | "TEMPLATE_INTENT" | "SEARCH_CONSOLE" | "SOCIAL_PAIN" | "DIRECT_THEME" | "PARTNER_THEME">;
  internalLinks: string[];
}

export interface CompetitorSeoSnapshot {
  version: 1;
  observedAt: string;
  refreshCadence: "MONTHLY";
  pages: CompetitorSeoPage[];
  opportunities: SeoGrowthOpportunity[];
  note: string;
}

export function scoreSeoOpportunity(item: Pick<SeoGrowthOpportunity, "postAwardFit" | "commercialIntent" | "productAlignment" | "freeFirstAwardFit" | "contentGap" | "templatePotential">) {
  return Math.round((item.postAwardFit + item.commercialIntent + item.productAlignment + item.freeFirstAwardFit + item.contentGap + item.templatePotential) / 6 * 10);
}

export function dedupeCompetitorPages(pages: readonly CompetitorSeoPage[]) {
  const byUrl = new Map<string, CompetitorSeoPage>();
  for (const page of pages) byUrl.set(page.url.replace(/\/$/, ""), page);
  return [...byUrl.values()];
}

export function recommendSeoOpportunity(item: SeoGrowthOpportunity, existingUrls: readonly string[]) {
  return item.existingPrimaryUrl && existingUrls.includes(item.existingPrimaryUrl) ? "EXPAND_EXISTING" as const : item.recommendation;
}

const observedAt = "2026-08-24T00:00:00.000Z";

/** Public URLs are evidence references only; no competitor prose is retained. */
const pages: CompetitorSeoPage[] = [
  { competitor: "Instrumentl", url: "https://www.instrumentl.com/templates/grant-report-template", title: "Grant Report Template for Nonprofits", pageType: "TEMPLATE", intent: "grant report template", observedAt },
  { competitor: "Instrumentl", url: "https://www.instrumentl.com/templates/grant-financial-report-template", title: "Grant Financial Report Template", pageType: "TEMPLATE", intent: "grant financial report template", observedAt },
  { competitor: "Instrumentl", url: "https://www.instrumentl.com/blog/how-to-guide-for-grant-reports", title: "How to Write Grant Reports [Template]", pageType: "HOW_TO", intent: "how to prepare a grant report", observedAt },
  { competitor: "Instrumentl", url: "https://www.instrumentl.com/blog/grant-tracking-spreadsheet-guide", title: "Easy To Use Grant Tracker Spreadsheet", pageType: "TEMPLATE", intent: "grant tracking spreadsheet", observedAt },
  { competitor: "Instrumentl", url: "https://www.instrumentl.com/templates", title: "Templates", pageType: "RESOURCE", intent: "practical grant-management templates", observedAt },
  { competitor: "Foundant / GrantHub", url: "https://smartsimple.foundant.com/products/granthub/", title: "Grant Management Software for Nonprofits", pageType: "COMMERCIAL_PRODUCT", intent: "full lifecycle nonprofit grant management software", observedAt },
  { competitor: "Foundant / GrantHub", url: "https://www.foundant.com/products/grant-management-software-for-foundations/", title: "Grant Management Software for Foundations", pageType: "COMMERCIAL_PRODUCT", intent: "grantmaker reporting and lifecycle software", observedAt },
  { competitor: "AmpliFund", url: "https://info.amplifund.com/grant-management-software-new-bing", title: "Grant Management: Amplify the Impact of Your Programs", pageType: "COMMERCIAL_PRODUCT", intent: "government grant management and reporting", observedAt },
  { competitor: "AmpliFund", url: "https://info.amplifund.com/blog/effective-grant-reporting", title: "3 Steps for Effective Grant Reporting", pageType: "HOW_TO", intent: "grant reporting workflow", observedAt },
  { competitor: "AmpliFund", url: "https://info.amplifund.com/webinar-playback-budgeting-financial-reporting-2", title: "Grant Budgeting & Financial Reporting Revisited", pageType: "RESOURCE", intent: "grant budget and financial reporting", observedAt },
  { competitor: "Submittable", url: "https://www.submittable.com/features/reporting", title: "Social Impact Reporting Software", pageType: "COMMERCIAL_PRODUCT", intent: "outcome and report collection", observedAt }
];

const make = (item: Omit<SeoGrowthOpportunity, "priorityScore">): SeoGrowthOpportunity => ({ ...item, priorityScore: scoreSeoOpportunity(item) });

const opportunities: SeoGrowthOpportunity[] = [
  make({ id: "seo-grant-reporting-software", priority: "P0", primaryQuery: "grant reporting software for nonprofits", userIntent: "Evaluate a practical post-award reporting workflow.", proposedUrl: "/grant-reporting-software", title: "Grant reporting software for nonprofits", pageType: "COMMERCIAL_LANDING_PAGE", recommendation: "NEW", competitorEvidence: [pages[5].url, pages[8].url], differentiatedValue: "A source-linked report-preparation workflow, not a broad lifecycle suite or a generic dashboard claim.", postAwardFit: 10, commercialIntent: 10, productAlignment: 10, freeFirstAwardFit: 10, contentGap: 9, templatePotential: 2, competition: "HIGH", sourceSignals: ["COMPETITOR_GAP", "COMMERCIAL_INTENT", "SEARCH_CONSOLE"], internalLinks: ["/blog/post-award-grant-management-software", "/assessment", "/sample-report"] }),
  make({ id: "seo-grant-financial-report-template", priority: "P0", primaryQuery: "grant financial report template", userIntent: "Get a usable financial-report starting point, then reconcile real figures.", proposedUrl: "/templates/grant-financial-report-template", title: "Grant financial report template", pageType: "TEMPLATE", recommendation: "NEW", competitorEvidence: [pages[1].url], differentiatedValue: "A downloadable, source-and-owner evidence matrix that shows budget-to-actual and supporting-document links—not a gated generic worksheet.", postAwardFit: 10, commercialIntent: 8, productAlignment: 9, freeFirstAwardFit: 10, contentGap: 10, templatePotential: 10, competition: "HIGH", sourceSignals: ["COMPETITOR_GAP", "TEMPLATE_INTENT", "COMMERCIAL_INTENT"], internalLinks: ["/blog/budget-to-actual-grant-reporting-workflow", "/assessment", "/sample-report"] }),
  make({ id: "seo-quickbooks-grant-reporting", priority: "P0", primaryQuery: "grant reporting with QuickBooks", userIntent: "Understand what the ledger can provide and what still needs a post-award workflow.", proposedUrl: "/blog/grant-reporting-with-quickbooks", title: "Grant reporting with QuickBooks: what still has to happen outside QBO", pageType: "ARTICLE", recommendation: "NEW", competitorEvidence: [pages[6].url, pages[9].url], differentiatedValue: "A concrete handoff from accounting export to approved budget, program update, evidence, and funder format.", postAwardFit: 10, commercialIntent: 9, productAlignment: 10, freeFirstAwardFit: 10, contentGap: 9, templatePotential: 5, competition: "MEDIUM", sourceSignals: ["COMPETITOR_GAP", "SOCIAL_PAIN", "DIRECT_THEME"], internalLinks: ["/blog/budget-to-actual-grant-reporting-workflow", "/assessment", "/sample-report"] }),
  make({ id: "seo-instrumentl-post-award-alternative", priority: "P0", primaryQuery: "Instrumentl alternative for grant reporting", userIntent: "Compare a broad grant-lifecycle product with a focused post-award report-preparation path.", proposedUrl: "/instrumentl-alternative-post-award-grant-reporting", title: "Instrumentl alternative for post-award grant reporting", pageType: "COMPARISON", recommendation: "NEW", competitorEvidence: [pages[2].url, pages[3].url], differentiatedValue: "A dated, sourced decision guide that narrows the comparison to report preparation after an award is received.", postAwardFit: 10, commercialIntent: 10, productAlignment: 9, freeFirstAwardFit: 10, contentGap: 8, templatePotential: 1, competition: "MEDIUM", sourceSignals: ["COMPETITOR_GAP", "COMMERCIAL_INTENT"], internalLinks: ["/grant-reporting-software", "/assessment", "/sample-report"] }),
  make({ id: "seo-grant-report-template", priority: "P0", primaryQuery: "grant report template", userIntent: "Start a report with an adaptable structure.", proposedUrl: "/templates/grant-report-template", title: "Grant report template for nonprofit teams", pageType: "TEMPLATE", recommendation: "NEW", competitorEvidence: [pages[0].url, pages[2].url], differentiatedValue: "A requirement-to-source workpaper that distinguishes narrative, financial, and evidence inputs.", postAwardFit: 10, commercialIntent: 8, productAlignment: 9, freeFirstAwardFit: 9, contentGap: 9, templatePotential: 10, competition: "HIGH", sourceSignals: ["COMPETITOR_GAP", "TEMPLATE_INTENT"], internalLinks: ["/blog/post-award-grant-reporting-checklist", "/assessment"] }),
  make({ id: "seo-budget-vs-actual-template", priority: "P0", primaryQuery: "grant budget vs actual template", userIntent: "Reconcile grant spending against the approved budget.", proposedUrl: "/templates/grant-budget-vs-actual-template", title: "Grant budget vs. actual template", pageType: "TEMPLATE", recommendation: "NEW", competitorEvidence: [pages[5].url, pages[9].url], differentiatedValue: "Includes a variance-explanation and source-document column designed for funder report review.", postAwardFit: 10, commercialIntent: 9, productAlignment: 10, freeFirstAwardFit: 10, contentGap: 9, templatePotential: 10, competition: "MEDIUM", sourceSignals: ["TEMPLATE_INTENT", "SOCIAL_PAIN", "DIRECT_THEME"], internalLinks: ["/blog/budget-to-actual-grant-reporting-workflow", "/assessment"] }),
  make({ id: "seo-grant-reporting-spreadsheet", priority: "P1", primaryQuery: "grant reporting spreadsheet", userIntent: "Use a spreadsheet safely until its handoffs and evidence trail become unmanageable.", proposedUrl: "/blog/grant-reporting-spreadsheet", title: "A grant reporting spreadsheet that does not lose the evidence trail", pageType: "ARTICLE", recommendation: "NEW", competitorEvidence: [pages[3].url], differentiatedValue: "A respectful spreadsheet starter plus decision criteria for moving to a source-linked workflow.", postAwardFit: 10, commercialIntent: 8, productAlignment: 9, freeFirstAwardFit: 9, contentGap: 9, templatePotential: 9, competition: "HIGH", sourceSignals: ["COMPETITOR_GAP", "SOCIAL_PAIN"], internalLinks: ["/blog/post-award-grant-management-software", "/assessment"] }),
  make({ id: "seo-grant-closeout-checklist-refresh", priority: "P1", primaryQuery: "grant closeout checklist", userIntent: "Finish an award with complete records and final reporting.", proposedUrl: "/blog/grant-closeout-checklist", title: "Grant closeout checklist", pageType: "CHECKLIST", recommendation: "EXPAND_EXISTING", existingPrimaryUrl: "/blog/grant-closeout-checklist", competitorEvidence: [pages[6].url], differentiatedValue: "Expand the existing page with a report-readiness and evidence handoff table.", postAwardFit: 10, commercialIntent: 7, productAlignment: 8, freeFirstAwardFit: 7, contentGap: 5, templatePotential: 8, competition: "MEDIUM", sourceSignals: ["SEARCH_CONSOLE", "COMPETITOR_GAP"], internalLinks: ["/assessment", "/sample-report"] }),
  make({ id: "seo-grant-reporting-calendar", priority: "P1", primaryQuery: "grant reporting calendar template", userIntent: "Work backward from report deadlines with named owners.", proposedUrl: "/templates/grant-reporting-calendar", title: "Grant reporting calendar template", pageType: "TEMPLATE", recommendation: "NEW", competitorEvidence: [pages[2].url, pages[3].url], differentiatedValue: "A workback plan linked to source collection, review, and open evidence gaps.", postAwardFit: 9, commercialIntent: 7, productAlignment: 8, freeFirstAwardFit: 8, contentGap: 10, templatePotential: 10, competition: "MEDIUM", sourceSignals: ["TEMPLATE_INTENT", "SOCIAL_PAIN"], internalLinks: ["/blog/post-award-grant-reporting-checklist", "/assessment"] }),
  make({ id: "seo-grant-report-requirements", priority: "P1", primaryQuery: "grant reporting requirements", userIntent: "Translate a specific award’s obligations into a workable report plan.", proposedUrl: "/blog/grant-reporting-requirements", title: "How to turn grant reporting requirements into a workable report plan", pageType: "PILLAR_GUIDE", recommendation: "NEW", competitorEvidence: [pages[2].url, pages[9].url], differentiatedValue: "Shows a requirements register with owners, source locations, and evidence instead of generic advice.", postAwardFit: 10, commercialIntent: 7, productAlignment: 10, freeFirstAwardFit: 8, contentGap: 9, templatePotential: 6, competition: "HIGH", sourceSignals: ["COMPETITOR_GAP", "SOCIAL_PAIN"], internalLinks: ["/blog/post-award-grant-reporting-checklist", "/assessment"] }),
  make({ id: "seo-multiple-grant-reporting", priority: "P1", primaryQuery: "how to manage reporting across multiple grants", userIntent: "Coordinate different deadlines and evidence requirements across awards.", proposedUrl: "/blog/manage-reporting-across-multiple-grants", title: "How to manage reporting across multiple grants", pageType: "ARTICLE", recommendation: "NEW", competitorEvidence: [pages[3].url, pages[5].url], differentiatedValue: "A practical operating model for separate award evidence, not a grant-finding tracker.", postAwardFit: 10, commercialIntent: 7, productAlignment: 9, freeFirstAwardFit: 8, contentGap: 10, templatePotential: 5, competition: "MEDIUM", sourceSignals: ["SOCIAL_PAIN", "DIRECT_THEME", "COMPETITOR_GAP"], internalLinks: ["/blog/post-award-grant-reporting-checklist", "/assessment"] }),
  make({ id: "seo-grant-evidence-checklist", priority: "P1", primaryQuery: "grant report supporting documentation", userIntent: "Know which proof supports reported financial and program claims.", proposedUrl: "/blog/funder-report-supporting-evidence-checklist", title: "What documents do you need for a funder report?", pageType: "CHECKLIST", recommendation: "EXPAND_EXISTING", existingPrimaryUrl: "/blog/funder-report-supporting-evidence-checklist", competitorEvidence: [pages[0].url], differentiatedValue: "Retain the source-linked checklist currently in founder review; do not create a duplicate URL.", postAwardFit: 10, commercialIntent: 8, productAlignment: 10, freeFirstAwardFit: 9, contentGap: 4, templatePotential: 8, competition: "MEDIUM", sourceSignals: ["COMPETITOR_GAP", "SOCIAL_PAIN"], internalLinks: ["/assessment", "/sample-report"] }),
  make({ id: "seo-grant-reporting-ownership", priority: "P1", primaryQuery: "who owns grant reporting", userIntent: "Assign finance, program, and grants responsibilities before a deadline.", proposedUrl: "/blog/who-owns-post-award-grant-reporting", title: "Who should own post-award grant reporting?", pageType: "ARTICLE", recommendation: "EXPAND_EXISTING", existingPrimaryUrl: "/blog/who-owns-post-award-grant-reporting", competitorEvidence: [pages[9].url], differentiatedValue: "Keep the existing founder-review draft as the primary answer rather than making a duplicate.", postAwardFit: 10, commercialIntent: 7, productAlignment: 9, freeFirstAwardFit: 7, contentGap: 4, templatePotential: 3, competition: "MEDIUM", sourceSignals: ["SOCIAL_PAIN", "PARTNER_THEME"], internalLinks: ["/assessment"] }),
  make({ id: "seo-granthub-alternative", priority: "P1", primaryQuery: "GrantHub alternative for grant reporting", userIntent: "Assess whether a broad post-award suite or focused report preparation is the better fit.", proposedUrl: "/granthub-alternative-grant-reporting", title: "GrantHub alternative for post-award grant reporting", pageType: "COMPARISON", recommendation: "NEW", competitorEvidence: [pages[5].url], differentiatedValue: "A narrow, sourced decision guide: full lifecycle administration versus source-linked report preparation.", postAwardFit: 9, commercialIntent: 9, productAlignment: 9, freeFirstAwardFit: 9, contentGap: 8, templatePotential: 1, competition: "MEDIUM", sourceSignals: ["COMPETITOR_GAP", "COMMERCIAL_INTENT"], internalLinks: ["/grant-reporting-software", "/assessment"] }),
  make({ id: "seo-post-award-reporting-guide", priority: "P1", primaryQuery: "post-award grant management", userIntent: "Set up a durable post-award operating workflow.", proposedUrl: "/blog/post-award-grant-reporting-guide", title: "Post-award grant reporting: a practical operating guide", pageType: "PILLAR_GUIDE", recommendation: "NEW", competitorEvidence: [pages[5].url, pages[8].url], differentiatedValue: "A pillar focused entirely on the report-preparation interval after award, including finance/program/evidence handoffs.", postAwardFit: 10, commercialIntent: 8, productAlignment: 10, freeFirstAwardFit: 9, contentGap: 8, templatePotential: 5, competition: "HIGH", sourceSignals: ["COMPETITOR_GAP", "COMMERCIAL_INTENT"], internalLinks: ["/blog/post-award-grant-reporting-checklist", "/assessment"] }),
  make({ id: "seo-grant-compliance-checklist", priority: "P2", primaryQuery: "grant compliance checklist", userIntent: "Prepare a compliant report without making legal claims.", proposedUrl: "/templates/grant-reporting-compliance-checklist", title: "Grant reporting compliance checklist", pageType: "CHECKLIST", recommendation: "NEW", competitorEvidence: [pages[8].url, pages[9].url], differentiatedValue: "A requirements-and-evidence checklist that directs users to their specific award terms.", postAwardFit: 9, commercialIntent: 8, productAlignment: 8, freeFirstAwardFit: 8, contentGap: 8, templatePotential: 9, competition: "HIGH", sourceSignals: ["TEMPLATE_INTENT", "COMPETITOR_GAP"], internalLinks: ["/blog/post-award-grant-reporting-checklist", "/assessment"] }),
  make({ id: "seo-grant-expense-tracking", priority: "P2", primaryQuery: "how to track grant expenses", userIntent: "Tie spend to award budget categories and reporting periods.", proposedUrl: "/blog/how-to-track-grant-expenses", title: "How to track grant expenses for a funder report", pageType: "ARTICLE", recommendation: "NEW", competitorEvidence: [pages[5].url, pages[9].url], differentiatedValue: "Focuses on reconciled inputs and variance support rather than generic bookkeeping.", postAwardFit: 9, commercialIntent: 8, productAlignment: 9, freeFirstAwardFit: 8, contentGap: 7, templatePotential: 6, competition: "HIGH", sourceSignals: ["SOCIAL_PAIN", "DIRECT_THEME"], internalLinks: ["/blog/budget-to-actual-grant-reporting-workflow", "/assessment"] }),
  make({ id: "seo-grant-progress-template", priority: "P2", primaryQuery: "grant progress report template", userIntent: "Prepare a program-and-financial status report.", proposedUrl: "/templates/grant-progress-report-template", title: "Grant progress report template", pageType: "TEMPLATE", recommendation: "NEW", competitorEvidence: [pages[4].url], differentiatedValue: "Pairs outcomes with source references, owner review, and open evidence gaps.", postAwardFit: 9, commercialIntent: 7, productAlignment: 8, freeFirstAwardFit: 8, contentGap: 8, templatePotential: 10, competition: "HIGH", sourceSignals: ["TEMPLATE_INTENT", "COMPETITOR_GAP"], internalLinks: ["/blog/grant-progress-report-workflow", "/assessment"] }),
  make({ id: "seo-grant-closeout-template", priority: "P2", primaryQuery: "grant closeout template", userIntent: "Prepare final reporting and record handoff.", proposedUrl: "/templates/grant-closeout-readiness-checklist", title: "Grant closeout readiness checklist", pageType: "CHECKLIST", recommendation: "NEW", competitorEvidence: [pages[5].url], differentiatedValue: "A final-report readiness checklist linked to a separate, existing closeout guide.", postAwardFit: 10, commercialIntent: 7, productAlignment: 8, freeFirstAwardFit: 7, contentGap: 8, templatePotential: 9, competition: "MEDIUM", sourceSignals: ["TEMPLATE_INTENT", "COMPETITOR_GAP"], internalLinks: ["/blog/grant-closeout-checklist", "/assessment"] }),
  make({ id: "seo-amplifund-alternative", priority: "P2", primaryQuery: "AmpliFund alternative for nonprofits", userIntent: "Choose between a government/enterprise grant platform and lightweight nonprofit report preparation.", proposedUrl: "/amplifund-alternative-post-award-reporting", title: "AmpliFund alternative for nonprofit post-award reporting", pageType: "COMPARISON", recommendation: "NEW", competitorEvidence: [pages[8].url, pages[9].url], differentiatedValue: "Only publish after a fresh feature/pricing review; position scope and deployment fit, not unsupported feature claims.", postAwardFit: 8, commercialIntent: 8, productAlignment: 7, freeFirstAwardFit: 8, contentGap: 7, templatePotential: 1, competition: "UNKNOWN", sourceSignals: ["COMPETITOR_GAP", "COMMERCIAL_INTENT"], internalLinks: ["/grant-reporting-software", "/assessment"] }),
  make({ id: "seo-grant-report-readiness-checker", priority: "P2", primaryQuery: "grant report readiness checklist", userIntent: "Find missing inputs before building a report.", proposedUrl: "/tools/grant-report-readiness-checker", title: "Grant report readiness checker", pageType: "CHECKLIST", recommendation: "NEW", competitorEvidence: [pages[2].url], differentiatedValue: "An intentionally lightweight checklist that naturally hands off to a real Free First Award—not a fake calculator.", postAwardFit: 10, commercialIntent: 8, productAlignment: 10, freeFirstAwardFit: 10, contentGap: 10, templatePotential: 8, competition: "LOW", sourceSignals: ["TEMPLATE_INTENT", "SOCIAL_PAIN", "COMPETITOR_GAP"], internalLinks: ["/assessment", "/sample-report"] }),
  make({ id: "seo-state-of-reporting-research", priority: "P2", primaryQuery: "nonprofit grant reporting benchmark", userIntent: "Find credible, original operational data.", proposedUrl: "/research/state-of-nonprofit-grant-reporting-2027", title: "State of nonprofit grant reporting 2027", pageType: "PILLAR_GUIDE", recommendation: "NEW", competitorEvidence: [pages[9].url], differentiatedValue: "Future original research only after a transparent survey and a predeclared respondent threshold; no fabricated statistics.", postAwardFit: 8, commercialIntent: 4, productAlignment: 7, freeFirstAwardFit: 4, contentGap: 10, templatePotential: 1, competition: "LOW", sourceSignals: ["PARTNER_THEME", "SOCIAL_PAIN"], internalLinks: ["/blog/post-award-grant-reporting-checklist"] })
];

export function buildCompetitorSeoSnapshot(): CompetitorSeoSnapshot {
  return { version: 1, observedAt, refreshCadence: "MONTHLY", pages: dedupeCompetitorPages(pages), opportunities: [...opportunities].sort((a, b) => b.priorityScore - a.priorityScore || a.id.localeCompare(b.id)), note: "Public URL/title/intent metadata only. Search volume is intentionally UNKNOWN unless first-party Search Console or a licensed provider supplies it." };
}
