import type { CompilationResult, SourceReference } from "../types/prototype";

export interface ProgramInsight {
  id: string;
  tone: "success" | "review" | "neutral";
  status: string;
  title: string;
  value: string;
  detail: string;
  sources: SourceReference[];
}

interface CountMetricDefinition {
  id: string;
  title: string;
  actual: RegExp;
  requirement: RegExp;
}

const countMetrics: CountMetricDefinition[] = [
  { id: "households-served", title: "Households served", actual: /served\s+(\d[\d,]*)\s+(?:unduplicated\s+)?households?/i, requirement: /(?:unduplicated\s+)?households?.*(?:served|receive|navigation)|(?:served|receive|navigation).*households?/i },
  { id: "housing-assessments", title: "Housing assessments", actual: /completed\s+(\d[\d,]*)\s+(?:housing(?:-related)?\s+)?assessments?/i, requirement: /housing(?:-related)?\s+assessments?|assessments?.*households?/i },
  { id: "housing-placements", title: "Housing placements", actual: /placed\s+(\d[\d,]*)\s+households?/i, requirement: /households?.*(?:placed|stable housing)|(?:placed|stable housing).*households?/i },
  { id: "benefits-screenings", title: "Benefits screenings", actual: /(?:benefits?\s+)?screening\s+for\s+(\d[\d,]*)\s+households?/i, requirement: /benefits?\s+screenings?|screenings?.*households?/i }
];

export function buildProgramInsights(result: Pick<CompilationResult, "narrative" | "requirements" | "programChecks">): ProgramInsight[] {
  const statements = result.narrative.filter((item) => item.status === "verified");
  const requirements = result.requirements.filter((item) => item.status === "verified");
  const insights: ProgramInsight[] = [];

  for (const metric of countMetrics) {
    const statement = statements.find((item) => metric.actual.test(item.text));
    if (!statement) continue;
    const actualMatch = statement.text.match(metric.actual);
    const actual = parseNumber(actualMatch?.[1]);
    if (actual === null) continue;
    const requirement = requirements.find((item) => metric.requirement.test(item.requirement));
    const target = requirement ? metricTarget(requirement.requirement, metric.requirement) : null;
    const progress = target && target > 0 ? roundOne((actual / target) * 100) : null;
    const achieved = target !== null && actual >= target;
    insights.push({
      id: metric.id,
      tone: achieved ? "success" : "neutral",
      status: achieved ? "Target achieved" : "Progress recorded",
      title: metric.title,
      value: target ? `${actual.toLocaleString()} of ${target.toLocaleString()}` : actual.toLocaleString(),
      detail: target
        ? `${progress}% of the cumulative grant target. No interim target was specified, so this is shown as cumulative progress rather than a schedule assessment.`
        : "Current-period result confirmed from the program update.",
      sources: compactSources([statement.source, requirement?.source])
    });
  }

  const retentionStatement = statements.find((item) => /remained.*(?:120\s*days|120-day)|retention/i.test(item.text) && /\d/.test(item.text));
  if (retentionStatement) {
    const ratio = retentionStatement.text.match(/Among\s+(\d[\d,]*)[^.]*?,\s*(\d[\d,]*)\s+(?:remained|were)[^.]*(?:120\s*days|120-day)/i);
    const eligible = parseNumber(ratio?.[1]);
    const retained = parseNumber(ratio?.[2]);
    const retentionRequirement = requirements.find((item) => /retention|remain(?:ed)?\s+(?:stably\s+)?housed/i.test(item.requirement) && /%/.test(item.requirement));
    const target = retentionRequirement ? percentValue(retentionRequirement.requirement) : null;
    if (eligible && retained !== null) {
      const actual = roundOne((retained / eligible) * 100);
      const achieved = target !== null && actual >= target;
      insights.push({
        id: "housing-retention",
        tone: achieved ? "success" : "neutral",
        status: achieved ? "Target achieved" : target === null ? "Result confirmed" : "Target not yet achieved",
        title: "120-day housing retention",
        value: `${actual}%${target !== null ? ` · target ${target}%` : ""}`,
        detail: `${retained} of ${eligible} eligible households remained housed at 120 days. The percentage is calculated from the confirmed counts, not generated by AI.`,
        sources: compactSources([retentionStatement.source, retentionRequirement?.source])
      });
    }
  }

  const satisfactionStatement = result.narrative.find((item) => /satisfaction/i.test(item.text) && /not confirmed|under validation|needs confirmation|information required/i.test(item.text));
  if (satisfactionStatement) {
    insights.push({
      id: "satisfaction-unconfirmed",
      tone: "review",
      status: "Not ready for reporting",
      title: "Client satisfaction",
      value: "Confirmation needed",
      detail: "The survey result is still being validated, so GrantDeskHQ keeps this KPI out of the report until the final value is confirmed.",
      sources: [satisfactionStatement.source]
    });
  }

  const leadership = leadershipNotificationInsight(result);
  if (leadership) insights.push(leadership);

  for (const check of (result.programChecks || []).filter((item) => item.type === "kpi_result" && item.severity !== "info" && item.resolution === "open")) {
    if (insights.some((item) => similar(item.title, check.title))) continue;
    insights.push({ id: `check-${check.id}`, tone: "review", status: "Needs review", title: check.title, value: "Information required", detail: check.detail, sources: check.sources });
  }

  return insights;
}

export function satisfiedProgramCheckIds(result: Pick<CompilationResult, "narrative" | "requirements" | "programChecks">) {
  const insights = buildProgramInsights(result);
  const leadershipSatisfied = insights.some((item) => item.id === "leadership-notification" && item.tone === "success");
  return new Set((result.programChecks || [])
    .filter((check) => leadershipSatisfied && check.type === "award_trigger" && /program director|leadership|staffing change/i.test(`${check.title} ${check.detail}`))
    .map((check) => check.id));
}

function leadershipNotificationInsight(result: Pick<CompilationResult, "narrative" | "requirements">): ProgramInsight | null {
  const statement = result.narrative.find((item) => /program director/i.test(item.text) && /resigned|leadership change|staffing change/i.test(item.text) && /notified/i.test(item.text));
  const requirement = result.requirements.find((item) => /program director|leadership|key personnel/i.test(item.requirement) && /business days?|notification|notify/i.test(item.requirement));
  if (!statement || !requirement || statement.status !== "verified" || requirement.status !== "verified") return null;
  const eventMatch = statement.text.match(/(?:resigned|change(?:d)?|occurred)(?:\s+(?:effective|on|as of))?\s+([A-Z][a-z]+\s+\d{1,2}(?:,\s*\d{4})?)/i);
  const noticeMatch = statement.text.match(/notified(?:\s+(?:the\s+)?funder)?(?:\s+on)?\s+([A-Z][a-z]+\s+\d{1,2}(?:,\s*\d{4})?)/i);
  const deadlineMatch = requirement.requirement.match(/within\s+(\d+)\s+business days?/i);
  const eventDate = parseHumanDate(eventMatch?.[1], statement.text);
  const noticeDate = parseHumanDate(noticeMatch?.[1], statement.text);
  const deadline = deadlineMatch ? Number(deadlineMatch[1]) : null;
  if (!eventDate || !noticeDate || !deadline) return null;
  const elapsed = businessDaysBetween(eventDate, noticeDate);
  const timely = elapsed <= deadline && noticeDate >= eventDate;
  return {
    id: "leadership-notification",
    tone: timely ? "success" : "review",
    status: timely ? "Requirement satisfied · Timely" : "Timing needs review",
    title: "Leadership-change notification",
    value: timely ? `Notified within ${elapsed} business ${elapsed === 1 ? "day" : "days"}` : `${elapsed} business days elapsed`,
    detail: `Program Director change: ${humanDate(eventDate)}. Funder notified: ${humanDate(noticeDate)}. Award requirement: notify within ${deadline} business days.`,
    sources: compactSources([statement.source, requirement.source])
  };
}

function metricTarget(value: string, metricPattern: RegExp) {
  const relevant = value.split(/[.;]/).find((part) => metricPattern.test(part)) || value;
  const values = [...relevant.matchAll(/\b(\d[\d,]*)\b/g)].map((match) => parseNumber(match[1])).filter((item): item is number => item !== null);
  return values.find((item) => item > 0 && item < 100_000) ?? null;
}

function percentValue(value: string) {
  const match = value.match(/(\d+(?:\.\d+)?)\s*%/);
  return match ? Number(match[1]) : null;
}

function parseNumber(value?: string) {
  if (!value) return null;
  const parsed = Number(value.replaceAll(",", ""));
  return Number.isFinite(parsed) ? parsed : null;
}

function parseHumanDate(value: string | undefined, context: string) {
  if (!value) return null;
  const year = value.match(/\d{4}/)?.[0] || context.match(/\b20\d{2}\b/)?.[0];
  const date = new Date(`${value.replace(/,?\s*\d{4}$/, "")}, ${year || new Date().getUTCFullYear()} 00:00:00 UTC`);
  return Number.isNaN(date.getTime()) ? null : date;
}

function businessDaysBetween(start: Date, end: Date) {
  let count = 0;
  const cursor = new Date(start);
  cursor.setUTCDate(cursor.getUTCDate() + 1);
  while (cursor <= end) {
    const day = cursor.getUTCDay();
    if (day !== 0 && day !== 6) count += 1;
    cursor.setUTCDate(cursor.getUTCDate() + 1);
  }
  return count;
}

function humanDate(value: Date) {
  return new Intl.DateTimeFormat("en-US", { month: "long", day: "numeric", year: "numeric", timeZone: "UTC" }).format(value);
}

function roundOne(value: number) {
  return Math.round(value * 10) / 10;
}

function compactSources(values: Array<SourceReference | undefined>) {
  return values.filter((value): value is SourceReference => Boolean(value)).filter((value, index, all) => all.findIndex((item) => item.sourceName === value.sourceName && item.locator === value.locator) === index);
}

function similar(left: string, right: string) {
  const words = (value: string) => new Set(value.toLowerCase().match(/[a-z]{4,}/g) || []);
  const leftWords = words(left);
  const rightWords = words(right);
  return [...leftWords].some((word) => rightWords.has(word));
}
