import { describe, expect, it } from "vitest";
import { aggregateBuyerLanguage, classifyConversionReply, classifyPartnerRelationship, dueFollowUps, resolveConversionLearningStatus, scoreProspect } from "../lib/gtmIntelligence";
describe("five-engine GTM intelligence primitives", () => {
  it("aggregates only source-backed buyer language without inventing quotes", () => { const themes = aggregateBuyerLanguage([{ phrase: "manual grant reconciliation", sourceType: "public forum", segment: "nonprofit finance", painCategory: "reconciliation", buyerStage: "problem aware", relevance: 11, observedAt: "2026-08-16", sourceUrl: "https://example.org/a" }, { phrase: "manual grant reconciliation", sourceType: "public forum", segment: "nonprofit finance", painCategory: "reconciliation", buyerStage: "problem aware", relevance: 8, observedAt: "2026-08-17", sourceUrl: "https://example.org/b" }, { phrase: "ignored", sourceType: "none", segment: "none", painCategory: "none", buyerStage: "none", relevance: 9, observedAt: "2026-08-17", sourceUrl: "not-a-url" }]); expect(themes).toHaveLength(1); expect(themes[0]).toMatchObject({ evidenceCount: 2, relevance: 10, lastObserved: "2026-08-17" }); });
  it("keeps prospect scores explainable and bounded", () => { const result = scoreProspect({ fit: 20, intent: 8, timing: 8, contactability: 7, procurementFriction: 2 }); expect(result.total).toBe(82); expect(result.explanation.join(" ")).toMatch(/procurement friction -2/); });
  it("classifies partner risk and conversion replies without an auto-send path", () => { expect(classifyPartnerRelationship({ scalesService: true, helpsClients: true, automatesBillableWork: false })).toBe("A"); expect(classifyPartnerRelationship({ scalesService: false, helpsClients: false, automatesBillableWork: true })).toBe("C"); expect(classifyConversionReply("Please remove me")).toBe("UNSUBSCRIBE"); expect(classifyConversionReply("We already use Instrumentl")).toBe("ALREADY_HAVE_SOLUTION"); });
  it("gives suppression precedence over every recorded conversion state", () => {
    expect(classifyConversionReply("I am interested, but please unsubscribe me")).toBe("UNSUBSCRIBE");
    expect(resolveConversionLearningStatus({ suppressionStatus: "BLOCKED", classification: "TRIAL_INTEREST", outcome: "WON", humanReviewed: true })).toBe("SUPPRESSED");
    expect(resolveConversionLearningStatus({ suppressionStatus: "CLEAR", classification: "UNSUBSCRIBE", outcome: "WON", humanReviewed: true })).toBe("SUPPRESSED");
  });
  it("never includes a suppressed or unreplied contact in follow-ups", () => { expect(dueFollowUps([{ id: "a", dueAt: "2026-08-16", suppressed: false, status: "SENT" }, { id: "b", dueAt: "2026-08-16", suppressed: true, status: "SENT" }, { id: "c", dueAt: "2026-08-16", suppressed: false, status: "REPLIED" }], "2026-08-17").map((item) => item.id)).toEqual(["a"]); });
});
