import { lookup } from "node:dns/promises";
import { listGtmChannelSeeds, saveGtmChannelSeed } from "./persistence.ts";
import { extractPublicOrganizationEvidence, readScrapeGraphCreditBalance, scrapeGraphBudgetAllowsCall, scrapeGraphRuntimeConfiguration } from "./scrapeGraphEvidence.ts";
import type { ChannelSeedRecord } from "../src/lib/gtmChannelSeeds.ts";

type Outcome = { canonicalRecordId: string; segment: ChannelSeedRecord["segment"]; disposition: "QUALIFIED" | "DEFERRED" | "REJECTED"; reason: string; providerHttpStatus?: number | null; providerRequestId?: string | null };

/** Scanner batches are organization research only. ScrapeGraphAI may extract
 * public evidence, but direct source checks remain the authority for canonical
 * qualification and no contact is inferred or enrolled here. */
export async function validateScannerSourceSeedsWithScrapeGraph(env: NodeJS.ProcessEnv = process.env) {
  const now = new Date().toISOString();
  const allSeeds = await listGtmChannelSeeds();
  const candidates = allSeeds.filter((seed) => seed.source === "chatgpt_scanner_drive" && scannerValidationDueForScrapeGraph(seed, now, env)).slice(0, configuredLimit(env));
  const configuration = scrapeGraphRuntimeConfiguration(env);
  const result = {
    selected: candidates.length, validated: 0, deferred: 0, rejected: 0, remediated: 0,
    provider: "scrapegraphai_extract+public_source", blocked: null as string | null,
    scrapeGraph: { configured: Boolean(configuration.enabled && configuration.apiKey), remainingCredits: null as number | null, creditsReserved: allSeeds.reduce((sum, seed) => sum + (seed.scrapeGraphEvidence?.creditsReserved || 0), 0), httpStatus: null as number | null, providerRequestId: null as string | null },
    outcomes: [] as Outcome[]
  };
  if (!configuration.enabled || !configuration.apiKey) return { ...result, blocked: "SCRAPEGRAPH_NOT_CONFIGURED" };
  const balance = await readScrapeGraphCreditBalance(configuration);
  result.scrapeGraph.remainingCredits = balance.remaining; result.scrapeGraph.httpStatus = balance.httpStatus; result.scrapeGraph.providerRequestId = balance.providerRequestId;
  if (balance.status !== "AVAILABLE") return { ...result, blocked: `SCRAPEGRAPH_${String(balance.errorCategory || "UNAVAILABLE").toUpperCase()}` };
  for (const seed of candidates) {
    const source = publicSource(seed.sourceUrl);
    if (!source) { await record(seed, "REJECTED", "UNSAFE_OR_MALFORMED_SOURCE_URL", "The scanner source is not a permitted public HTTPS URL.", now, env); result.rejected++; result.outcomes.push(outcome(seed, "REJECTED", "UNSAFE_OR_MALFORMED_SOURCE_URL")); continue; }
    if (!await sourceSupportsOrganizationSignal(source, seed.organization, seed.segment)) { await record(seed, "REJECTED", "SOURCE_CLAIM_NOT_INDEPENDENTLY_VERIFIED", "The public discovery source did not support the organization identity and segment signal.", now, env); result.rejected++; result.outcomes.push(outcome(seed, "REJECTED", "SOURCE_CLAIM_NOT_INDEPENDENTLY_VERIFIED")); continue; }
    if (!scrapeGraphBudgetAllowsCall({ creditsAlreadyReserved: result.scrapeGraph.creditsReserved, providerRemaining: balance.remaining, configuration })) { result.blocked = "SCRAPEGRAPH_CREDIT_HEADROOM_REACHED"; break; }
    const nextAttempt = (seed.validationAttemptCount || 0) + 1;
    const reserved = { requestId: `reserved_${seed.id}_${nextAttempt}`, sourceUrl: source.toString(), officialOrganizationUrl: null, officialOrganizationName: null, evidenceSummary: null, contactSourceUrl: null, creditsReserved: nextScrapeGraphReservedCredits(seed.scrapeGraphEvidence?.creditsReserved || 0, configuration.extractCreditCost), extractedAt: now };
    await saveGtmChannelSeed({ ...seed, lifecycle: "ROLE_UNRESOLVED", validationDisposition: "DEFERRED", validationAttemptCount: nextAttempt, validationLastAttemptAt: now, validationNextAttemptAt: retryAt(now, nextAttempt), enrichmentProvider: "scrapegraphai", enrichmentProviderStatus: "PROCESSING", enrichmentResult: "ScrapeGraphAI public-source extraction is in progress; no identity, contact, or email is inferred.", enrichmentUpdatedAt: now, scrapeGraphEvidence: reserved });
    result.scrapeGraph.creditsReserved += configuration.extractCreditCost;
    const extracted = await extractPublicOrganizationEvidence({ sourceUrl: source.toString(), organization: seed.organization, segment: seed.segment, configuration });
    if (extracted.status === "UNAVAILABLE") { const reason = `SCRAPEGRAPH_${String(extracted.errorCategory || "UNAVAILABLE").toUpperCase()}`; await record({ ...seed, scrapeGraphEvidence: reserved }, "DEFERRED", reason, "The public evidence extractor did not return a result; the record remains deferred without a generated contact.", now, env, extracted.httpStatus, extracted.requestId); result.deferred++; result.outcomes.push(outcome(seed, "DEFERRED", reason, extracted.httpStatus, extracted.requestId)); if (["authentication", "insufficient_credits", "rate_limited"].includes(String(extracted.errorCategory))) { result.blocked = reason; break; } continue; }
    const official = publicSource(extracted.officialOrganizationUrl || "");
    if (!official || !await officialSourceSupportsOrganization(official, seed.organization)) { await record({ ...seed, scrapeGraphEvidence: { ...reserved, requestId: extracted.requestId || reserved.requestId, officialOrganizationUrl: extracted.officialOrganizationUrl, officialOrganizationName: extracted.officialOrganizationName, evidenceSummary: extracted.evidenceSummary, contactSourceUrl: extracted.contact?.sourceUrl || null, extractedAt: now } }, "DEFERRED", "OFFICIAL_DOMAIN_NOT_INDEPENDENTLY_VERIFIED", "The extractor returned no independently verifiable official organization domain. The record remains deferred.", now, env, extracted.httpStatus, extracted.requestId); result.deferred++; result.outcomes.push(outcome(seed, "DEFERRED", "OFFICIAL_DOMAIN_NOT_INDEPENDENTLY_VERIFIED", extracted.httpStatus, extracted.requestId)); continue; }
    const domain = official.hostname.toLowerCase().replace(/^www\./, "");
    const contact = extracted.contact && roleFits(seed.segment, extracted.contact.title) && extracted.contact.email.endsWith(`@${domain}`) && await pageSupportsPublishedContact(source, seed.organization, extracted.contact) ? { ...extracted.contact, observedAt: now } : null;
    await saveGtmChannelSeed({ ...seed, lifecycle: "EVIDENCE_QUALIFIED", organizationDomain: domain, officialOrganizationUrl: official.toString(), officialOrganizationEvidenceUrl: official.toString(), qualificationProvider: "scrapegraphai_extract+public_source", qualificationUpdatedAt: now, validationDisposition: "QUALIFIED", validationAttemptCount: nextAttempt, validationLastAttemptAt: now, validationNextAttemptAt: null, rejectionReason: null, scannerValidatedContact: contact, scrapeGraphEvidence: { ...reserved, requestId: extracted.requestId || reserved.requestId, officialOrganizationUrl: official.toString(), officialOrganizationName: extracted.officialOrganizationName, evidenceSummary: extracted.evidenceSummary, contactSourceUrl: contact?.sourceUrl || null, extractedAt: now }, enrichmentProvider: "scrapegraphai", enrichmentProviderStatus: contact ? "COMPLETED" : "PROCESSING", enrichmentResult: contact ? "ScrapeGraphAI located an explicitly published role-fit work email. Instantly verification is required before readiness." : "Organization evidence qualified. A public current role-fit email remains unresolved and will be checked only on official organization pages.", enrichmentUpdatedAt: now, qualificationReasons: [...seed.qualificationReasons, "Public source independently supports the segment signal.", "Official organization domain independently verified after ScrapeGraphAI extraction."] });
    result.validated++; result.outcomes.push(outcome(seed, "QUALIFIED", contact ? "EVIDENCE_QUALIFIED_PUBLIC_CONTACT" : "EVIDENCE_QUALIFIED_CONTACT_UNRESOLVED", extracted.httpStatus, extracted.requestId));
  }
  return result;
}

async function record(seed: ChannelSeedRecord, disposition: "DEFERRED" | "REJECTED", reason: string, detail: string, now: string, env: NodeJS.ProcessEnv, httpStatus: number | null = null, requestId: string | null = null) {
  const attempts = (seed.validationAttemptCount || 0) + 1;
  const exhausted = disposition === "DEFERRED" && attempts >= configuredMaxAttempts(env);
  const final = exhausted ? "REJECTED" : disposition;
  await saveGtmChannelSeed({ ...seed, lifecycle: final === "REJECTED" ? "REJECTED" : "ROLE_UNRESOLVED", rejectionReason: exhausted ? `${reason}_RETRY_EXHAUSTED` : reason, enrichmentProvider: "scrapegraphai", enrichmentProviderStatus: final === "REJECTED" ? "FAILED" : "PROCESSING", enrichmentLastProviderError: httpStatus ? `${reason} HTTP_${httpStatus}${requestId ? ` REQUEST_${requestId}` : ""}`.slice(0, 500) : reason, enrichmentResult: detail, qualificationProvider: "scrapegraphai_extract+public_source", qualificationUpdatedAt: now, validationDisposition: final, validationAttemptCount: attempts, validationLastAttemptAt: now, validationNextAttemptAt: final === "DEFERRED" ? retryAt(now, attempts) : null, enrichmentUpdatedAt: now });
}
function outcome(seed: ChannelSeedRecord, disposition: Outcome["disposition"], reason: string, providerHttpStatus: number | null = null, providerRequestId: string | null = null): Outcome { return { canonicalRecordId: seed.id, segment: seed.segment, disposition, reason, providerHttpStatus, providerRequestId }; }
export function scannerValidationDueForScrapeGraph(seed: ChannelSeedRecord, now: string, env: NodeJS.ProcessEnv = process.env) { if (seed.lifecycle === "DISCOVERED") return true; if (seed.lifecycle !== "ROLE_UNRESOLVED") return false; const attempts = seed.validationAttemptCount || 0; if (attempts >= configuredMaxAttempts(env)) return false; if (seed.validationDisposition && seed.validationDisposition !== "DEFERRED") return false; const next = Date.parse(seed.validationNextAttemptAt || ""); return !Number.isFinite(next) || next <= Date.parse(now); }
/** Retries consume credits too; a later attempt can never reset the durable per-record accounting. */
export function nextScrapeGraphReservedCredits(existing: number, extractCreditCost: number) { return Math.max(0, Number.isFinite(existing) ? existing : 0) + Math.max(0, Number.isFinite(extractCreditCost) ? extractCreditCost : 0); }
function configuredLimit(env: NodeJS.ProcessEnv) { const value = Number(env.GTM_SCRAPEGRAPH_MAX_PER_RUN || env.GTM_SCANNER_VALIDATION_MAX_PER_RUN || 10); return Number.isInteger(value) && value > 0 ? Math.min(value, 10) : 10; }
function configuredMaxAttempts(env: NodeJS.ProcessEnv) { const value = Number(env.GTM_SCANNER_VALIDATION_MAX_ATTEMPTS || 3); return Number.isInteger(value) && value >= 1 ? Math.min(value, 5) : 3; }
function retryAt(now: string, attempts: number) { return new Date(Date.parse(now) + Math.min(24 * 60 * 60 * 1_000, 15 * 60 * 1_000 * 2 ** Math.max(0, attempts - 1))).toISOString(); }
async function sourceSupportsOrganizationSignal(source: URL, organization: string, segment: ChannelSeedRecord["segment"]) { const text = await publicText(source); return mentionsOrganization(text, organization) && (segment === "DIRECT" ? /grant|funder|restricted fund|compliance|budget|report/.test(text) : /nonprofit|fractional cfo|accounting|grant|fiscal|controller/.test(text)); }
async function officialSourceSupportsOrganization(source: URL, organization: string) { return mentionsOrganization(await publicText(source), organization); }
async function pageSupportsPublishedContact(source: URL, organization: string, contact: { fullName: string; title: string; email: string }) { const text = await publicText(source); return mentionsOrganization(text, organization) && text.includes(contact.fullName.toLowerCase()) && text.includes(contact.email.toLowerCase()) && text.includes(contact.title.toLowerCase()); }
function roleFits(segment: ChannelSeedRecord["segment"], title: string) { return segment === "DIRECT" ? /\b(cfo|finance|controller|grants|executive director|chief operating)\b/i.test(title) : /\b(founder|ceo|partner|principal|fractional cfo|director)\b/i.test(title); }
function mentionsOrganization(text: string, organization: string) { const parts = organization.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim().split(" ").filter((part) => part.length > 2); return parts.length > 0 && parts.every((part) => text.includes(part)); }
async function publicText(source: URL) { try { const addresses = await lookup(source.hostname, { all: true, verbatim: true }); if (!addresses.length || addresses.some((entry) => privateAddress(entry.address))) return ""; const response = await fetch(source, { redirect: "error", headers: { Accept: "text/html,application/pdf;q=0.9" }, signal: AbortSignal.timeout(15_000) }); if (!response.ok || Number(response.headers.get("content-length") || 0) > 512_000) return ""; const text = await boundedText(response, 512_000); return text.toLowerCase().replace(/[^a-z0-9@._+-]+/g, " "); } catch { return ""; } }
async function boundedText(response: Response, maximum: number) { const reader = response.body?.getReader(); if (!reader) return ""; const chunks: Uint8Array[] = []; let size = 0; try { while (true) { const { done, value } = await reader.read(); if (done) break; size += value.byteLength; if (size > maximum) { await reader.cancel(); return ""; } chunks.push(value); } } finally { reader.releaseLock(); } const bytes = new Uint8Array(size); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; } return new TextDecoder().decode(bytes); }
function privateAddress(address: string) { const value = address.toLowerCase(); return value === "::1" || value.startsWith("fe80:") || value.startsWith("fc") || value.startsWith("fd") || /^(127\.|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.)/.test(value); }
function publicSource(value: string) { try { const url = new URL(value); const host = url.hostname.toLowerCase().replace(/^www\./, ""); return url.protocol === "https:" && !url.username && !url.password && !/^(localhost|metadata\.google\.internal|127\.|10\.|192\.168\.|169\.254\.)/.test(host) ? url : null; } catch { return null; } }
